# this file is used for configuration of kitchen dokken
# for integration tests in the CI
---
driver:
  name: dokken
  privileged: true # because Docker and SystemD/Upstart
  chef_version: <%= ENV['CHEF_VERSION'] || 'latest' %>

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  name: inspec
  sudo: true

platforms:
- name: amazonlinux-1
  driver:
    image: dokken/amazonlinux
    pid_one_command: /sbin/init
- name: amazonlinux-2
  driver:
    image: dokken/amazonlinux-2
    pid_one_command: /usr/lib/systemd/systemd
- name: centos-6
  driver:
    image: dokken/centos-6
    pid_one_command: /sbin/init
- name: centos-7
  driver:
    image: dokken/centos-7
    pid_one_command: /usr/lib/systemd/systemd
- name: centos-8
  driver:
    image: dokken/centos-8
    pid_one_command: /usr/lib/systemd/systemd
- name: oracle-6
  driver:
    image: oraclelinux:6
- name: oracle-7
  driver:
    image: oraclelinux:7
    pid_one_command: /usr/lib/systemd/systemd
- name: debian-9
  driver:
    image: dokken/debian-9
    intermediate_instructions:
    - RUN /usr/bin/apt-get update
    pid_one_command: /bin/systemd
- name: debian-10
  driver:
    image: dokken/debian-10
    intermediate_instructions:
    - RUN /usr/bin/apt-get update
    pid_one_command: /bin/systemd
- name: fedora-28
  driver:
    image: dokken/fedora-28
    pid_one_command: /usr/lib/systemd/systemd
    intermediate_instructions:
    - RUN dnf install -y yum
- name: fedora-29
  driver:
    image: dokken/fedora-29
    pid_one_command: /usr/lib/systemd/systemd
    intermediate_instructions:
    - RUN dnf install -y yum
- name: opensuse-42
  driver:
    image: dokken/opensuse-leap
    pid_one_command: /bin/systemd
- name: ubuntu-16-04
  driver:
    image: dokken/ubuntu-16.04
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
- name: ubuntu-18-04
  driver:
    image: dokken/ubuntu-18.04
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
